## 2.6 `scipy.linalg`: Álgebra Linear Avançada

In [1]:
from scipy.linalg import lu
from scipy import stats
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Matriz de exemplo


In [2]:
A = np.array([[3, 2, 1], [1, 1, 1], [0, 1, 2]])


# Decomposição LU


In [3]:
P, L, U = lu(A)
print("Matriz L:")
print(L)
print("Matriz U:")
print(U)

Matriz L:
[[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.33333333 0.33333333 1.        ]]
Matriz U:
[[3. 2. 1.]
 [0. 1. 2.]
 [0. 0. 0.]]
